# Generated by Django 4.1.5 on 2023-01-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catName',
            new_name='cat_name',
        ),
    ]
